import type { Course, UDLChecklist } from '@/types/course'
import type { AuditReport, AuditIssue, AuditSeverity } from './audit-engine'
import { udlChecklistScore, udlPillarScores } from '@/lib/course-helpers'

const SEVERITY_COLORS: Record<AuditSeverity, string> = {
  critical: '#dc2626',
  serious: '#ea580c',
  moderate: '#d97706',
  minor: '#6b7280'
}

/**
 * Render accessibility audit report as HTML suitable for PDF generation.
 */
export function renderAuditPdfHtml(course: Course, report: AuditReport): string {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; font-size: 11pt; line-height: 1.6; }
  .page { padding: 40px 50px; }

  /* Cover Page */
  .cover { text-align: center; padding: 120px 50px 40px; }
  .cover h1 { font-size: 28pt; color: #1e293b; margin-bottom: 8px; }
  .cover .subtitle { font-size: 14pt; color: #64748b; margin-bottom: 40px; }
  .cover .course-title { font-size: 18pt; color: #7c3aed; margin-bottom: 4px; }
  .cover .date { font-size: 11pt; color: #94a3b8; }
  .cover .score-circle {
    display: inline-flex; align-items: center; justify-content: center;
    width: 100px; height: 100px; border-radius: 50%; border: 4px solid;
    font-size: 32pt; font-weight: 700; margin: 30px 0;
  }

  h2 { font-size: 16pt; color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin: 30px 0 16px; }
  h3 { font-size: 13pt; color: #334155; margin: 20px 0 10px; }

  .summary-grid { display: flex; gap: 12px; margin-bottom: 24px; }
  .summary-card {
    flex: 1; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0;
    text-align: center;
  }
  .summary-card .count { font-size: 24pt; font-weight: 700; }
  .summary-card .label { font-size: 9pt; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }

  .issue { padding: 12px 16px; border: 1px solid #e2e8f0; border-radius: 8px; margin-bottom: 8px; border-left: 4px solid; }
  .issue .title { font-weight: 600; font-size: 11pt; }
  .issue .meta { font-size: 9pt; color: #64748b; margin-top: 2px; }
  .issue .description { font-size: 10pt; color: #475569; margin-top: 6px; }
  .issue .suggestion { font-size: 10pt; color: #7c3aed; margin-top: 4px; font-style: italic; }

  .udl-section { margin-bottom: 20px; }
  .udl-bar { height: 8px; background: #e2e8f0; border-radius: 4px; margin: 6px 0 12px; overflow: hidden; }
  .udl-bar-fill { height: 100%; border-radius: 4px; }
  .check-item { padding: 4px 0; font-size: 10pt; }
  .check-item .icon { margin-right: 6px; }

  .reading-table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  .reading-table th { background: #f1f5f9; padding: 8px 12px; text-align: left; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #e2e8f0; }
  .reading-table td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; font-size: 10pt; }

  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 9pt; color: #94a3b8; }

  @media print { .page-break { page-break-before: always; } }
</style>
</head>
<body>

<!-- Cover Page -->
<div class="cover">
  <h1>Accessibility Audit Report</h1>
  <p class="subtitle">WCAG 2.1 AA & Universal Design for Learning</p>
  <div class="score-circle" style="border-color: ${scoreColor(report.score)}; color: ${scoreColor(report.score)}">
    ${report.score}
  </div>
  <p class="course-title">${escapeHtml(course.meta.title)}</p>
  <p class="date">${now} &bull; ${course.meta.author}</p>
</div>

<!-- Executive Summary -->
<div class="page page-break">
  <h2>Executive Summary</h2>
  <div class="summary-grid">
    <div class="summary-card">
      <div class="count" style="color: ${scoreColor(report.score)}">${report.score}/100</div>
      <div class="label">Overall Score</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: ${SEVERITY_COLORS.critical}">${report.summary.critical}</div>
      <div class="label">Critical</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: ${SEVERITY_COLORS.serious}">${report.summary.serious}</div>
      <div class="label">Serious</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: ${SEVERITY_COLORS.moderate}">${report.summary.moderate}</div>
      <div class="label">Moderate</div>
    </div>
    <div class="summary-card">
      <div class="count" style="color: ${SEVERITY_COLORS.minor}">${report.summary.minor}</div>
      <div class="label">Minor</div>
    </div>
  </div>
  <p>This report was generated by analyzing <strong>${course.modules.length} module(s)</strong> and <strong>${course.modules.reduce((s, m) => s + m.lessons.length, 0)} lesson(s)</strong> for WCAG 2.1 AA compliance and UDL alignment.</p>

  <!-- Issues by Severity -->
  <h2>Issues by Severity</h2>
  ${renderIssuesBySection(report.issues)}
</div>

<!-- UDL Checklist -->
<div class="page page-break">
  <h2>UDL Checklist</h2>
  ${course.modules.map((mod) => renderUDLModule(mod.title, mod.udlChecklist)).join('')}
</div>

<!-- Reading Levels -->
<div class="page page-break">
  <h2>Reading Level Analysis</h2>
  ${report.readingLevels.length > 0 ? `
  <table class="reading-table">
    <thead>
      <tr>
        <th>Lesson</th>
        <th>Grade Level</th>
        <th>Words</th>
        <th>Sentences</th>
        <th>Avg Words/Sentence</th>
      </tr>
    </thead>
    <tbody>
      ${report.readingLevels.filter(r => r.wordCount > 0).map(r => `
        <tr>
          <td>${escapeHtml(r.lessonTitle)}</td>
          <td style="color: ${gradeLevelColor(r.gradeLevel)}; font-weight: 600">${r.gradeLevel ?? '—'}</td>
          <td>${r.wordCount}</td>
          <td>${r.sentenceCount}</td>
          <td>${r.avgWordsPerSentence}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  ` : '<p>No text content to analyze.</p>'}
</div>

<div class="footer">
  Generated by Course Clip Studio &bull; ${now}
</div>

</body>
</html>`
}

function renderIssuesBySection(issues: AuditIssue[]): string {
  const severities: AuditSeverity[] = ['critical', 'serious', 'moderate', 'minor']
  let html = ''

  for (const severity of severities) {
    const filtered = issues.filter(i => i.severity === severity)
    if (filtered.length === 0) continue

    html += `<h3 style="color: ${SEVERITY_COLORS[severity]}">${capitalize(severity)} (${filtered.length})</h3>`
    for (const issue of filtered) {
      html += `
        <div class="issue" style="border-left-color: ${SEVERITY_COLORS[severity]}">
          <div class="title">${escapeHtml(issue.title)}</div>
          <div class="meta">${escapeHtml(issue.criterion)} &bull; ${escapeHtml(issue.lessonTitle)}</div>
          <div class="description">${escapeHtml(issue.description)}</div>
          <div class="suggestion">${escapeHtml(issue.suggestion)}</div>
        </div>
      `
    }
  }

  if (issues.length === 0) {
    html += '<p style="color: #16a34a; font-weight: 600">No accessibility issues found. Great job!</p>'
  }

  return html
}

function renderUDLModule(title: string, checklist: UDLChecklist): string {
  const scores = udlPillarScores(checklist)
  const total = udlChecklistScore(checklist)

  return `
    <div class="udl-section">
      <h3>${escapeHtml(title)} — ${total.checked}/${total.total} items</h3>

      <p><strong>Representation</strong> (${scores.representation}%)</p>
      <div class="udl-bar"><div class="udl-bar-fill" style="width: ${scores.representation}%; background: #3b82f6"></div></div>
      ${renderChecklist(checklist.representation, {
        multipleFormats: 'Multiple content formats',
        altTextPresent: 'Alt text on all images',
        transcriptsPresent: 'Transcripts on audio/video',
        captionsPresent: 'Captions on video',
        readingLevelAppropriate: 'Appropriate reading level'
      })}

      <p><strong>Action & Expression</strong> (${scores.action}%)</p>
      <div class="udl-bar"><div class="udl-bar-fill" style="width: ${scores.action}%; background: #8b5cf6"></div></div>
      ${renderChecklist(checklist.action, {
        keyboardNavigable: 'Fully keyboard navigable',
        multipleResponseModes: 'Multiple response modes',
        sufficientTime: 'Sufficient time for tasks'
      })}

      <p><strong>Engagement</strong> (${scores.engagement}%)</p>
      <div class="udl-bar"><div class="udl-bar-fill" style="width: ${scores.engagement}%; background: #f59e0b"></div></div>
      ${renderChecklist(checklist.engagement, {
        choiceAndAutonomy: 'Learner choice and autonomy',
        relevantContext: 'Relevant, meaningful context',
        feedbackPresent: 'Feedback on assessments',
        progressVisible: 'Progress tracking visible'
      })}
    </div>
  `
}

function renderChecklist(data: Record<string, boolean>, labels: Record<string, string>): string {
  return Object.entries(labels).map(([key, label]) => {
    const checked = data[key] ?? false
    return `<div class="check-item"><span class="icon">${checked ? '✅' : '⬜'}</span>${escapeHtml(label)}</div>`
  }).join('')
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function scoreColor(score: number): string {
  if (score >= 80) return '#16a34a'
  if (score >= 50) return '#d97706'
  return '#dc2626'
}

function gradeLevelColor(grade: number | null): string {
  if (grade === null) return '#6b7280'
  if (grade <= 8) return '#16a34a'
  if (grade <= 12) return '#d97706'
  return '#dc2626'
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
