/**
 * Educator Learner Progress Report Renderer
 *
 * Generates printable WCAG-tagged HTML reports from learner progress data.
 * Supports: HTML (inline print), CSV (raw data export).
 * PDF is generated by printing the HTML via the browser print dialog.
 */

import type {
  EducatorReportData,
  EducatorReportOptions,
  LearnerProgressRecord,
  ActivityLogEntry
} from '@/types/analytics'
import { generateActivityLog, activityLogToPlainText } from './activity-log-generator'
import type { LuminaStatement } from '@/types/analytics'

// ─── HTML Report Generation ───

export function generateEducatorReportHTML(data: EducatorReportData, options: EducatorReportOptions): string {
  const { courseTitle, generatedAt, generatedBy, learners, courseSummary } = data
  const dateStr = new Date(generatedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  })

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Educator Learner Progress Report — ${escHtml(courseTitle)}</title>
<style>
  @media print {
    .no-print { display: none !important; }
    .page-break { page-break-before: always; }
  }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 24px; color: #1e293b; line-height: 1.5; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 18px; margin-top: 32px; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }
  h3 { font-size: 15px; margin-top: 20px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { padding: 8px 10px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
  th { background: #f8fafc; font-weight: 600; }
  .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0; }
  .summary-card { background: #f8fafc; border-radius: 8px; padding: 14px; text-align: center; }
  .summary-card .value { font-size: 24px; font-weight: 700; color: #e11d8f; }
  .summary-card .label { font-size: 11px; color: #94a3b8; margin-top: 2px; }
  .status-met { color: #166534; font-weight: 600; }
  .status-approaching { color: #92400e; font-weight: 600; }
  .status-not-yet { color: #991b1b; font-weight: 600; }
  .activity-entry { padding: 4px 0; font-size: 12px; color: #475569; border-bottom: 1px solid #f1f5f9; }
  .activity-time { color: #94a3b8; margin-right: 8px; }
  .meta { font-size: 12px; color: #94a3b8; }
  .ferpa-notice { background: #fffbeb; border: 1px solid #fde68a; border-radius: 6px; padding: 10px; font-size: 11px; color: #92400e; margin: 12px 0; }
</style>
</head>
<body>
<div class="no-print" style="margin-bottom:20px;">
  <button onclick="window.print()" style="padding:8px 20px;background:#e11d8f;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:14px;">Print / Save as PDF</button>
</div>

<h1>Educator Learner Progress Report</h1>
<p class="meta">${escHtml(courseTitle)} &mdash; Generated ${dateStr} by ${escHtml(generatedBy)}</p>
${data.dateRange ? `<p class="meta">Date range: ${data.dateRange.start} to ${data.dateRange.end}</p>` : ''}

${!options.anonymize ? '<div class="ferpa-notice">This report contains identified learner data. Handle in accordance with your institution\'s FERPA policy.</div>' : ''}

<h2>Course Overview</h2>
<div class="summary-grid" role="list" aria-label="Course summary metrics">
  <div class="summary-card" role="listitem"><div class="value">${courseSummary.enrollments}</div><div class="label">Enrollments</div></div>
  <div class="summary-card" role="listitem"><div class="value">${Math.round(courseSummary.completionRate)}%</div><div class="label">Completion Rate</div></div>
  <div class="summary-card" role="listitem"><div class="value">${Math.round(courseSummary.averageScore)}%</div><div class="label">Avg Score</div></div>
  <div class="summary-card" role="listitem"><div class="value">${formatDuration(courseSummary.averageTimeSeconds)}</div><div class="label">Avg Time</div></div>
</div>

<h2>Learner Progress</h2>
<table aria-label="Learner progress table">
  <thead>
    <tr>
      <th scope="col">Learner</th>
      <th scope="col">Completion</th>
      <th scope="col">Avg Score</th>
      <th scope="col">Time Spent</th>
      <th scope="col">Last Activity</th>
    </tr>
  </thead>
  <tbody>
${learners.map((l) => `    <tr>
      <td>${escHtml(l.learnerDisplayName || l.learnerId)}</td>
      <td>${l.courseCompletionPercent}%</td>
      <td>${computeAvgScore(l)}%</td>
      <td>${formatDuration(l.totalTimeSeconds)}</td>
      <td>${l.lastActivity ? new Date(l.lastActivity).toLocaleDateString() : 'N/A'}</td>
    </tr>`).join('\n')}
  </tbody>
</table>

${learners.map((l, idx) => `
${idx > 0 ? '<div class="page-break"></div>' : ''}
<h3>${escHtml(l.learnerDisplayName || l.learnerId)} — Detail</h3>

${l.assessmentScores.length > 0 ? `
<h4 style="font-size:13px;margin-top:12px;">Assessment Scores</h4>
<table aria-label="Assessment scores for ${escHtml(l.learnerDisplayName || l.learnerId)}">
  <thead><tr><th scope="col">Assessment</th><th scope="col">Score</th><th scope="col">Status</th><th scope="col">Attempts</th></tr></thead>
  <tbody>
${l.assessmentScores.map((a) => `    <tr><td>${escHtml(a.blockName)}</td><td>${Math.round(a.score)}%</td><td class="${a.passed ? 'status-met' : 'status-not-yet'}">${a.passed ? 'Passed' : 'Not passed'}</td><td>${a.attempts}</td></tr>`).join('\n')}
  </tbody>
</table>` : ''}

${l.knowledgeCheckPhaseScores.length > 0 ? `
<h4 style="font-size:13px;margin-top:12px;">Knowledge Check Phase Scores</h4>
<table aria-label="Phase scores for ${escHtml(l.learnerDisplayName || l.learnerId)}">
  <thead><tr><th scope="col">Objective</th><th scope="col">Pre</th><th scope="col">Post</th><th scope="col">Change</th></tr></thead>
  <tbody>
${l.knowledgeCheckPhaseScores.map((p) => `    <tr><td>${escHtml(p.objective)}</td><td>${p.preScore != null ? p.preScore + '%' : 'N/A'}</td><td>${p.postScore != null ? p.postScore + '%' : 'N/A'}</td><td>${p.delta != null ? (p.delta >= 0 ? '+' : '') + p.delta + '%' : 'N/A'}</td></tr>`).join('\n')}
  </tbody>
</table>` : ''}

${l.udlPathwaysUsed.length > 0 ? `
<h4 style="font-size:13px;margin-top:12px;">UDL Pathways Used</h4>
<ul style="font-size:13px;color:#475569;margin:4px 0;padding-left:20px;">
${l.udlPathwaysUsed.map((p) => `  <li>${escHtml(p)}</li>`).join('\n')}
</ul>` : ''}

${options.includeActivityLog && l.activityLog.length > 0 ? `
<h4 style="font-size:13px;margin-top:12px;">Activity Log</h4>
${l.activityLog.slice(-20).map((entry) => `<div class="activity-entry"><span class="activity-time">${new Date(entry.timestamp).toLocaleString()}</span>${escHtml(entry.plainLanguageSummary)}</div>`).join('\n')}` : ''}
`).join('\n')}

<div style="margin-top:40px;padding-top:12px;border-top:1px solid #e2e8f0;">
  <p class="meta">Generated by Course Clip Studio &mdash; LuminaUDL Analytics</p>
</div>
</body>
</html>`
}

// ─── CSV Export ───

export function generateEducatorReportCSV(data: EducatorReportData): string {
  const headers = [
    'Learner ID',
    'Display Name',
    'Completion %',
    'Average Score',
    'Total Time (min)',
    'Last Activity',
    'UDL Pathways Used'
  ]

  const rows = data.learners.map((l) => [
    l.learnerId,
    l.learnerDisplayName || '',
    String(l.courseCompletionPercent),
    String(computeAvgScore(l)),
    String(Math.round(l.totalTimeSeconds / 60)),
    l.lastActivity || '',
    l.udlPathwaysUsed.join('; ')
  ])

  return [headers.join(','), ...rows.map((r) => r.map(csvEscape).join(','))].join('\n')
}

// ─── Build Report Data ───

export function buildLearnerProgressRecords(
  statements: LuminaStatement[],
  identityResolver: (id: string) => string
): LearnerProgressRecord[] {
  const byActor = new Map<string, LuminaStatement[]>()
  for (const s of statements) {
    if (!byActor.has(s.actorId)) byActor.set(s.actorId, [])
    byActor.get(s.actorId)!.push(s)
  }

  const records: LearnerProgressRecord[] = []
  for (const [actorId, actorStmts] of byActor) {
    const sorted = [...actorStmts].sort((a, b) => a.timestamp.localeCompare(b.timestamp))
    const displayName = identityResolver(actorId)

    // Assessment scores
    const assessmentScores: LearnerProgressRecord['assessmentScores'] = []
    const passedOrFailed = sorted.filter((s) =>
      s.verb.includes('/passed') || s.verb.includes('/failed')
    )
    const byBlock = new Map<string, LuminaStatement[]>()
    for (const s of passedOrFailed) {
      const key = s.blockId || s.objectId
      if (!byBlock.has(key)) byBlock.set(key, [])
      byBlock.get(key)!.push(s)
    }
    for (const [blockId, blockStmts] of byBlock) {
      const latest = blockStmts[blockStmts.length - 1]
      assessmentScores.push({
        blockId,
        blockName: latest.objectName || blockId,
        score: latest.scoreScaled != null ? Math.round(latest.scoreScaled * 100) : (latest.scoreRaw ?? 0),
        passed: latest.verb.includes('/passed'),
        attempts: blockStmts.length
      })
    }

    // KC phase scores
    const kcStmts = sorted.filter((s) => s.verb.includes('/answered') && s.phase && s.objectives?.length)
    const objPhases = new Map<string, { pre: number[]; post: number[] }>()
    for (const s of kcStmts) {
      for (const obj of s.objectives!) {
        if (!objPhases.has(obj)) objPhases.set(obj, { pre: [], post: [] })
        const bucket = s.phase === 'pre' ? objPhases.get(obj)!.pre : objPhases.get(obj)!.post
        bucket.push(s.success ? 1 : 0)
      }
    }
    const phaseScores: LearnerProgressRecord['knowledgeCheckPhaseScores'] = []
    for (const [obj, d] of objPhases) {
      const pre = d.pre.length > 0 ? Math.round((d.pre.reduce((a, b) => a + b, 0) / d.pre.length) * 100) : null
      const post = d.post.length > 0 ? Math.round((d.post.reduce((a, b) => a + b, 0) / d.post.length) * 100) : null
      phaseScores.push({
        objective: obj,
        preScore: pre,
        postScore: post,
        delta: pre != null && post != null ? post - pre : null
      })
    }

    // UDL pathways
    const udlVerbs = sorted.filter((s) => s.udlPrinciple)
    const udlPathways = [...new Set(udlVerbs.map((s) => s.verbDisplay))]

    // Time
    const totalTime = sorted.reduce((sum, s) => sum + (s.durationSeconds ?? 0), 0)

    // Completion
    const completedItems = sorted.filter((s) => s.completion)
    const totalItems = new Set(sorted.map((s) => s.objectId)).size
    const completionPercent = totalItems > 0 ? Math.round((completedItems.length / totalItems) * 100) : 0

    // Activity log
    const logGroups = generateActivityLog(sorted, 'third-person')
    const activityLog: ActivityLogEntry[] = logGroups.flatMap((g) => g.entries)

    records.push({
      learnerId: actorId,
      learnerDisplayName: displayName !== actorId ? displayName : undefined,
      courseCompletionPercent: Math.min(completionPercent, 100),
      moduleProgress: [],
      assessmentScores,
      knowledgeCheckPhaseScores: phaseScores,
      udlPathwaysUsed: udlPathways,
      totalTimeSeconds: totalTime,
      lastActivity: sorted[sorted.length - 1]?.timestamp ?? '',
      activityLog
    })
  }

  return records.sort((a, b) => (a.learnerDisplayName || a.learnerId).localeCompare(b.learnerDisplayName || b.learnerId))
}

// ─── Helpers ───

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function csvEscape(s: string): string {
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return '"' + s.replace(/"/g, '""') + '"'
  }
  return s
}

function formatDuration(seconds: number): string {
  if (seconds < 60) return `${seconds}s`
  const m = Math.floor(seconds / 60)
  if (m < 60) return `${m}m`
  const h = Math.floor(m / 60)
  return `${h}h ${m % 60}m`
}

function computeAvgScore(l: LearnerProgressRecord): number {
  if (l.assessmentScores.length === 0) return 0
  return Math.round(l.assessmentScores.reduce((sum, a) => sum + a.score, 0) / l.assessmentScores.length)
}
